name: Temporarily test changelog formatting
on:
  pull_request:

jobs:
  build:
    name: Get changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Python tools
        uses: BrandonLWhite/pipx-install-action@v0.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install dependencies
        run: poetry install --with=release --extras=docs

      - name: Install pandoc
        run: sudo apt update && sudo apt install pandoc -y

      - name: Obtain the changelog
        id: generate_changelog
        run: |-
          {
            echo "### Commit: ${{ github.sha }}"
            echo "### Changelog:"
            echo
            poe --quiet changelog
          } > changelog.md

      - name: Store the changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.md
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: build
    steps:
      - name: Retrieve the changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog
          path: changelog.md

      - uses: mshick/add-pr-comment@v2
        with:
          message-path: changelog.md
